version: '2'

services:

  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0 --sql_mode=""
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql
    env_file:
        - variables.env

  memcached:
    image: memcached:1.4-alpine
    ports:
      - "11211:11211"

  queue:
    image: phalconphp/beanstalkd:1.10
    ports:
      - "11300:11300"
    volumes:
      - beanstalk:/var/lib/beanstalkd

  elasticsearch:
    image: elasticsearch:5.2-alpine
    expose:
      - "9200"
      - "9300"
    ports:
      - "9200:9200"
      - "9300:9300"
    env_file:
      - variables.env
    volumes:
      - esdata:/usr/share/elasticsearch/data  

  app:
    build: docker/app
    working_dir: /project
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/project
      - ./conf/php/cli.ini:/etc/php/7.0/cli/conf.d/100-custom.ini
      - ./conf/php/fpm.ini:/etc/php/7.0/fpm/conf.d/100-custom.ini
      - ./conf/apache/sites-enabled:/etc/apache2/sites-enabled
    depends_on:
      - mysql
      - queue
      - memcached
      - elasticsearch
    env_file:
      - variables.env

volumes:
  mysql:
    driver: local
  beanstalk:
    driver: local
  esdata:
    driver: local
